### ISSUE TITLE
[react-native]After adding Sqlite to the project, Error occurs 

### ISSUE THREAD

**Issue by Niks77** [andpor/react-native-sqlite-storage#294] opened 2018-09-16 10:52 UTC
![capture42](https://user-images.githubusercontent.com/38828554/45595463-d94bf900-b9c9-11e8-9776-b864845f93aa.PNG)

### My React Native Project  configuration is
`{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.5.0",
    "react-native": "0.57.0",
    "react-native-sqlite-storage": "^3.3.6"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "^0.45.0",
    "react-test-renderer": "16.5.0"
  },
  "jest": {
    "preset": "react-native"
  }
}`
### In setting.gradle
` rootProject.name = 'AwesomeProject' `

`include ':react-native-sqlite-storage'
project(':react-native-sqlite-storage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sqlite-storage/src/android')`

`include ':app`'
`
### In Android/app/build.gradle
`dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
     compile project(':react-native-sqlite-storage') 
}`
### In MainApllication.java
...`import org.pgsqlite.SQLitePluginPackage;`...

...`@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new SQLitePluginPackage(),
          new MainReactPackage()
      );
    }`...

Thankyou for helping Me
P.s :- Sorry of My Bad English

**Comment by filippoitaliano** [comment] 2018-10-03 10:45
@Niks77 Have you found any solution?

**Comment by filippoitaliano** [comment] 2018-10-04 13:16
After some tries I was able to install and link correctly the package. It built in both android and IOS with no errors. Then trying to open a new db I discovered another problem: this one [#285](https://github.com/andpor/react-native-sqlite-storage/issues/285). I've reinstalled many times the package, in a clean rn project, following line by line the readme.

**Comment by sameerjain** [comment] 2018-10-05 07:11
@filippoitaliano If you are using prepopulated database then you may want to test this https://github.com/sameerjain/SQLiteDemo and see if that compile well and run as expected on android.

**Comment by filippoitaliano** [comment] 2018-10-05 07:55
@sameerjain Thank you! It doesn't build on IOS but is very usefull!!

**Comment by sameerjain** [comment] 2018-10-05 07:59
@filippoitaliano yeah, I used cipher lib which needed extra steps to build on ios. But this should take you in right direction :)

**Comment by wolfjobs** [comment] 2018-10-17 15:09
I solve my problem with upgrade the version of  `compileSdk`&`targetSdk` to 26;

**Comment by tonycapone** [comment] 2018-12-10 22:07
Has anyone fixed this? It looks like the problem is that jcenter is missing the gradle dependency and that is the only repository listed in the `build.gradle`

`buildscript {
    repositories {
        jcenter()
    }
`

**Comment by spruce-bruce** [comment] 2018-12-10 22:43
I've been using this lib for close to a year now with minimal problems, but my builds are suddenly spitting out this error. 

Is the issue that jcenter dropped that dep and this lib has no way of resolving it otherwise?

**Comment by spruce-bruce** [comment] 2018-12-11 17:48
@tonycapone The PR I submitted fixed the issue for me. For now I've got `    "react-native-sqlite-storage": "git://github.com:spruce-bruce/react-native-sqlite-storage.git#resolve-gradle-dep",
` in my package.json and that allows my builds to succeed. Once my PR is merged I'll be able to switch back to the npm module

**Closed** 2018-12-12 17:53 UTC

**Comment by DedoJr** [comment] 2019-07-05 15:07
@filippoitaliano
...
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules

    **implementation** project(':react-native-sqlite-storage')
}
...

**Comment by filippoitaliano** [comment] 2019-07-05 15:41
@DedoJr Yeah, we are in 2019.

**Comment by agatheLG** [comment] 2019-09-09 15:54
Hi, I had a lot of dependencies errors after trying to install react-native-sqlite-storage and i solved it by changing the path in the settings.gradle : I replace 
 project(':react-native-sqlite-storage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sqlite-storage/src/android')
by
project(':react-native-sqlite-storage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sqlite-storage/platforms/android')

Another thing was that I didn't put anything in the mainApplication file, I din't add any package, which gives me this :
 @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      return packages;
    }

I hope it helps

**Comment by ironbunny-ib** [comment] 2020-07-20 12:01
Which settings.gradle?
I do not have any mention of react native sqlite storage in my android/settings.gradle

`rootProject.name = 'LoveCopy'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
`
