### ISSUE TITLE
Not able to 'select *' in android

### ISSUE THREAD

**Issue by mukeshsoni** [andpor/react-native-sqlite-storage#16] opened 2015-12-28 14:57 UTC
I tried going through various examples in https://github.com/litehelpers/Cordova-sqlite-storage too.

I can connect to the db alright and even execute and 'insert into table...' query. But when i then do a 'select * from <tablename>' query, i get this error - 

```
Expected receiver of type org.json.JSONArray, but got java.lang.reflect.Field
```

The code i am trying out right now is -

```
var SQLite = require('react-native-sqlite-storage');
function errorCB(err) {
  console.log("SQL Error: " + err);
}

function successCB() {
  console.log("SQL executed fine");
}

function openCB() {
  console.log("Database OPENED");
}

var db = SQLite.openDatabase("test.db", "1.0", "Test Database", 200000, openCB, errorCB);
db.executeSql("DROP TABLE IF EXISTS tt");
db.executeSql("CREATE TABLE tt (data)");
db.transaction((tx) => {
  tx.executeSql("INSERT INTO tt values (?)", 'something', successCB, errorCB);
}, (err) => {
  console.log('transaction error: ', err.message);
}, () => {
  db.executeSql('select count(*) from tt', [], (res) => {
    console.log('got count: ', JSON.stringify(res.rows.item(0)));
  }, (err) => {
    console.log('error getting count: ', err.message);
  });
});
```

Am i doing anything incorrect?

A simpler form of above comes back with the same error - 

```
var db = SQLite.openDatabase("test.db", "1.0", "Test Database", 200000, openCB, errorCB);
db.executeSql("DROP TABLE IF EXISTS tt");
db.executeSql("CREATE TABLE tt (data)");
db.transaction((tx) => {
  // tx.executeSql("INSERT INTO tt values (?)", 'something', successCB, errorCB);
  tx.executeSql("SELECT LENGTH('tenletters') AS stringlength", [], function(tx, res) {
    console.log('got stringlength: ' + res.rows.item(0).stringlength);
  });
}, (err) => {
  console.log('transaction error: ', err.message);
});
```

**Comment by andpor** [comment] 2015-12-28 16:30
which version of the code are you running? Is it first time you're trying and it worked before / now broken or this is fresh?

**Comment by andpor** [comment] 2015-12-28 16:32
Also , is this Android native or generic?

**Comment by andpor** [comment] 2015-12-28 16:33
Can you attach some portion of the Android log file?

**Comment by mukeshsoni** [comment] 2015-12-28 16:39
1. This is the first time i am trying it.
2. "is this Android native or generic" - I don't get the question
3. The error seems to be from android. Will try to grab more logs and paste.

**Comment by andpor** [comment] 2015-12-28 16:45
#2 - there are two flavors on Android - one is native the other one is pure Java. Which one are you trying?

can you try making the following code change in the constructor for
SQLiteObject.java
            valuesField.set(this, new LinkedHashMap<String, Object>(size));
SQLiteArray.java
            valuesField.set(this, new ArrayList<>(size));

And see if that is the root cause ?

**Comment by andpor** [comment] 2015-12-28 16:52
I committed the fix. Can you try and let me know if the issue is resolved? It works for me.

**Comment by mukeshsoni** [comment] 2015-12-28 16:54
compiling... so i also need to import ArrayList? `import java.util.ArrayList;`

**Comment by mukeshsoni** [comment] 2015-12-28 17:01
Contents of SQLiteObject.java - 

```
package org.pgsqlite;

import org.json.JSONObject;

import java.lang.reflect.Field;
import java.util.LinkedHashMap;
import java.util.ArrayList;
/**
 * Created by aporebsk on 11/28/15.
 *
 * Overwrite default JSONObject implementation to allow creation of object using initial load factor
 */
public class SQLiteObject extends JSONObject {
    public SQLiteObject(){
        super();
    }

    public SQLiteObject(int size){
        super();
        try {
            Field valuesField = JSONObject.class.getDeclaredField("nameValuePairs");
            valuesField.setAccessible(true);
            valuesField.set(valuesField, new ArrayList<>(size));
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
    }
}
```

There was no change to be made to SQLiteArray.java file. 

Still getting the same error.

**Comment by mukeshsoni** [comment] 2015-12-28 17:01
I am running this on genymotion emulator, if it's of any help.

**Comment by andpor** [comment] 2015-12-28 17:04
get the latest code from this repo. It has the fixes.

**Closed** 2015-12-28 17:06 UTC

**Comment by mukeshsoni** [comment] 2015-12-28 17:07
Yup, works. Copy paste caused the error (valuesField.set(this, new LinkedHashMap(size));).

Thanks a lot!
