### ISSUE TITLE
Duplicate interface definition for class RCTBridge

### ISSUE THREAD

**Issue by amourya-systango** [andpor/react-native-sqlite-storage#123] opened 2017-02-01 11:53 UTC
With new react native version 0.40 react-native-sqlite-storage library is not building. It's giving Duplicate interface definition for class RCTBridge compile time error

**Comment by itinance** [comment] 2017-02-01 11:55
Duplicate of #112 

upcoming release will fix this. See https://github.com/andpor/react-native-sqlite-storage/issues/112#issuecomment-272131117

**Closed** 2017-02-01 13:40 UTC
